version: '3'

services:
  api:
    build: 
      context: api
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
      restart: always
      build: 
        context: nginx
      ports:
        - "${EXTERNAL_PORT}:80"
      volumes:
        - ./api:/www

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"